					<div id="left_content">
                       
                        <p class="title">HANDICRAFT- HISTORY</p>
 <p class="mycontent">
   <img src="<?php echo $this->config->base_url('assets/images/IMG_7192.jpg'); ?> "  />                   
Throughout history and in many societies including Nepal, gender inequality was part of an accepted male-dominated culture. Atrocities and discrimination are the two major problems, which the Nepalese women face in the present day society. The traditional mentalities of Nepal assume that the place of women is mainly concentrated to the household activities like kitchen work and upbringing of the children. They have been considered as the sex object and inferior to the men in different spheres of knowledge. The Polygamy System', 'Child Marriage', 'Dowry System', etc. have been some form of atrocities and discriminatory attitudes against the women. Even after fifty nine years of democracy, women are still one of the most powerless and marginalized section of Nepali society. In Nepal, women's representation in public leadership is very low in comparison to the other developing countries. In our country many men have been living in two marriages, because Hindu accepts polygamy system where the husband has more than two wives. So, many husbands have two wives and neglect their first wife and their children, due to this reason many children are helpless and many of them are in street. So, if we are able to make women independent through giving them work and making them financially strong, we hope maximum numbers of the children will get support from their mother. Nepalese women are the most deprived and neglected group of society. They face discrimination at every field like at home, at office, at work, in law and in society. They have less access to healthy nutrition and to health education. This could be one of the causes of the low life expectation for Nepalese women (53.9 years, compared to 56.1 years of Men). In almost all Nepalese societies gender is significant of social stratification Men's roles are generally more highly valued and rewarded then women's roles: in almost every family woman bear the primary responsibility for child care and domestic work, while men have traditionally borne responsibility for providing the family livelihood. It is said that the prevailing division of labour between the sexes has led to men and women assuming unequal positions in terms of power, prestige and wealth. Because of the lack of sufficient financial condition Nepali women were victims of domestic violence, forceful marriage, marriages with big age differences, physical and sexual violence. Many girls are trafficked for sex workers and many are in prostitute business for earning their daily bread. So, we are able to establish a small industry and able to give a secure job for them - at least few girls life will be better, few children will get shelter, food and education, few women will get family life and few lives will be saved through our small handicraft projects
</p>
</div><!--end of left content-->
<div id="left_content">

<p class="title">HANDICRAFT IN NEPAL</p>
 <p class="mycontent">  
    <img src="<?php echo $this->config->base_url('assets/images/DSC07261.jpg'); ?> "  />     
                
The term 'handicraft' encompasses a wide range of artifacts. The informal sector, which includes handicrafts, has been described by International Labour Organization (ILO) as a part of economic activity characterized by certain features like reliance on local available resources and skills, family ownership, small scale operations, and labour intensity. Handicraft was first introduced in Nepal with the financial and technical support of UNICEF with the objective to meet the marketing requirements of handicraft producers who are mainly women and operating on a very small scale, usually from their homes. There are many kinds of handicraft production in Nepal, some of them are Nepali Paper, Rice Paper, Bamboo Crafts, Dhaka Clothes, paper envelope, greeting cards, handbag, money bag, wallet, mobile cover, paper plate, water bottle cover and many more.</p>
						</div><!--end of left content-->